# Generated by Django 3.2.25 on 2024-04-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=250),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
