# Generated by Django 3.2.25 on 2024-04-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240414_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Meat & Poultry', 'Meat & Poultry'), ('Seafood', 'Seafood'), ('Dairy & Eggs', 'Dairy & Eggs'), ('Fruits & Vegetables', 'Fruits & Vegetables'), ('Grains & Flour', 'Grains & Flour'), ('Spices & Seasonings', 'Spices & Seasonings'), ('Snacks & Sweets', 'Snacks & Sweets'), ('Frozen Foods', 'Frozen Foods'), ('Canned & Packaged Foods', 'Canned & Packaged Foods'), ('Drinks', 'Drinks')], max_length=250),
        ),
    ]
